#!/usr/bin/env python3

import pathlib
import os
import sys
import subprocess

base_dir = sys.argv[1] if len(sys.argv) == 3 else "/mnt/ssd-shared"
with open(f"{base_dir}/.links","r") as f:
    link_patterns = [l.strip() for l in f.readlines() if len(l.strip()) > 0]

target_dir = sys.argv[2] if len(sys.argv) == 3 else "/home/tadeas"

subprocess.Popen([f"{base_dir}/pre_setup_links", target_dir])

def setup_link(source, target):
    path_obj = pathlib.Path(target)
    if path_obj.is_symlink() and path_obj.resolve() == path:
        return
    elif not path_obj.exists():
        os.symlink(source, target)
    else:
        print(f"Skipping {target} because already exists")


for pat in link_patterns:
    path = f"{base_dir}/{pat}"
    if path[:-1] == "/":
        path = path[:-1]
    if not os.path.isfile(path) and not os.path.isdir(path):
        print(f"Pattern for {path} not matching any dir/file in {base_dir}")
        continue
    if pat.endswith("/"):
        for item in os.listdir(path):
            setup_link(f"{path}/{item}", f"{target_dir}/{pat}{item}")
    else:
        setup_link(path, f"{target_dir}/{pat}")

subprocess.Popen([f"{base_dir}/post_setup_links", target_dir])

